#!/usr/bin/env ruby
# Usage: novac secgroup-list [pattern]
# Summary: List all Security Group Rules (except ping)
# Help: Pattern is an optional parameter to filter the group list.
# eg. novac secgroup-list 0.0.0.0 will show all rules that are open to the world.

$:.unshift File.expand_path("../../share/novac/lib/rb", __FILE__)
require 'rubygems'
require 'terminal-table'
require 'novadb2'
require 'helpers/projects'

# Ensure root or sudo is used for this command
if Process.euid != 0
  throw "Must run this script as root or use sudo."
end

projects = Projects.new.projects

p = nil
if ARGV[0]
  p = ARGV[0]
else
  puts "Project name or ID is required"
  exit 1
end

# Objects
projects = Projects.new
novadb = NovaDB2.instance

# Get the OpenStack Query Library
os_release = novadb.get_openstack_release
require "openstack/#{os_release}"
openstack = Object.const_get(os_release.capitalize).new

# Get the project id
project = projects.fuzzy_search(p)
project_id = project.keys[0]
project_name = project.values[0]

rows = []
novadb.regions.each do |region, creds|
  openstack.secgroups_by_project(project_id, region).each do |row|
    rows << [ project_name, row[:from_port], row[:to_port], row[:cidr] ]
  end
end

# Print report
headings = [ 'Project', 'Start Port', 'End Port', 'CIDR' ]

table = Terminal::Table.new :headings => headings, :rows => rows
puts table

