#!/usr/bin/env ruby

# Usage: novac user-artifacts <user name>
# Summary: Lists all resources that a user has created (projects, instances, volumes)
# Help: "project name" is required.

$:.unshift File.expand_path("../../share/novac/lib/rb", __FILE__)
require 'rubygems'
require 'novadb'
require 'projects'
require 'users'

required_libs = ['terminal-table','mysql2']

# Try to load each of the libraries
# Fail if unable to and list what libs are needed
begin
  required_libs.each { |l| require l }
rescue LoadError
  puts "This script needs the following external libraries: "
  required_libs.each { |l| puts " * #{l}" }
  exit 1
end

# Ensure root or sudo is used for this command
if Process.euid != 0
  throw "Must run this script as root or use sudo."
end

# Was a project name specified?
if ARGV[0]
  u = ARGV[0]
else
  puts "User name or ID is required"
  exit 1
end

# Objects
novadb = NovaDB.new
master = novadb.master_cloud
users = Users.new
db = Mysql2::Client.new(:host => master[:server], :username => master[:username], :password => master[:password])

user = users.fuzzy_search(u)
user_name = user.values[0]
user_id = user.keys[0]

puts "User: #{user_name}"
puts "ID: #{user_id}"

puts "Projects"
users.projects(user_id).each do |project|
  puts "* #{project}"
end
puts ""

novadb.clouds.each do |region, creds|
  db.close if db
  db = Mysql2::Client.new(:host => creds[:server], :username => master[:username], :password => master[:password])

  instances_query = "select instances.id, instances.display_name from nova.instances where instances.user_id = '#{user_id}' and deleted = 0 order by display_name"
  instance_list = db.query(instances_query)
  puts "Instances in #{region} (#{instance_list.count})"
  instance_list.each(:as => :hash) do |row|
    puts "* #{row['display_name']}"
  end
  puts ""

  volumes_query = "select volumes.id, volumes.display_name from cinder.volumes where volumes.user_id = '#{user_id}' and deleted = 0 order by display_name"
  volume_list = db.query(volumes_query)
  puts "Volumes in #{region} (#{volume_list.count})"
  volume_list.each(:as => :hash) do |row|
    puts "* #{row['display_name']}"
  end
  puts ""
end
