#!/usr/bin/env ruby
$:.unshift File.expand_path("../../share/novac/lib/rb", __FILE__)
require 'rubygems'
require 'novadb'
require 'quotas'

# variables
project_id = ARGV[0]
limit = ARGV[1]

quotas = Quotas.new

object_mb = quotas.used(project_id)['object_mb']
if object_mb
  puts object_mb
else
  puts 0
end
