#!/usr/bin/env ruby

# Usage: novac user-artifacts <user name>
# Summary: Lists all resources that a user has created (projects, instances, volumes)
# Help: "project name" is required.

$:.unshift File.expand_path("../../share/novac/lib/rb", __FILE__)
require 'rubygems'
require 'novadb'
require 'projects'

required_libs = ['terminal-table','mysql2']

# Try to load each of the libraries
# Fail if unable to and list what libs are needed
begin
  required_libs.each { |l| require l }
rescue LoadError
  puts "This script needs the following external libraries: "
  required_libs.each { |l| puts " * #{l}" }
  exit 1
end

# Ensure root or sudo is used for this command
if Process.euid != 0
  throw "Must run this script as root or use sudo."
end

# Was a project name specified?
if ARGV[0]
  u = ARGV[0]
else
  puts "User name or ID is required"
  exit 1
end

# Objects
novadb = NovaDB.new
master = novadb.master_cloud

db = Mysql2::Client.new(:host => master[:server], :username => master[:username], :password => master[:password])

# Was a user ID given?
user_id = nil
user_query = "select id from keystone.user where id = '#{u}'"
db.query(user_query).each(:as => :hash) do |row|
  user_id = row['id']
end

# Was a user name given?
unless user_id
  user_query = "select id from keystone.user where name = '#{u}'"
  db.query(user_query).each(:as => :hash) do |row|
    user_id = row['id']
  end
end

# Nothing found
unless user_id
  puts "User not found."
  exit 1
end

puts "User #{u}"
puts "ID: #{user_id}"
puts ""

project_query = "select project.name from keystone.user_project_metadata inner join keystone.user on keystone.user_project_metadata.user_id = keystone.user.id inner join keystone.project on keystone.project.id = keystone.user_project_metadata.project_id where keystone.user.id = '#{user_id}' order by project.name"
project_list = db.query(project_query)
puts "Projects (#{project_list.count})"
project_list.each(:as => :hash) do |row|
  puts "* #{row['name']}"
end
puts ""

db.close if db

novadb.clouds.each do |region, creds|
  db = Mysql2::Client.new(:host => creds[:server], :username => master[:username], :password => master[:password])

  instances_query = "select instances.id, instances.display_name from nova.instances where instances.user_id = '#{user_id}' and deleted = 0 order by display_name"
  instance_list = db.query(instances_query)
  puts "Instances in #{region} (#{instance_list.count})"
  instance_list.each(:as => :hash) do |row|
    puts "* #{row['display_name']}"
  end
  puts ""

  volumes_query = "select volumes.id, volumes.display_name from cinder.volumes where volumes.user_id = '#{user_id}' and deleted = 0 order by display_name"
  volume_list = db.query(volumes_query)
  puts "Volumes in #{region} (#{volume_list.count})"
  volume_list.each(:as => :hash) do |row|
    puts "* #{row['display_name']}"
  end
  puts ""
end
