#!/usr/bin/env ruby

# Usage: novac user-artifacts <user name>
# Summary: Lists all resources that a user has created (projects, instances, volumes)
# Help: "project name" is required.

$:.unshift File.expand_path("../../share/novac/lib/rb", __FILE__)
require 'rubygems'
require 'novadb2'
require 'helpers/projects'
require 'helpers/users'

# Ensure root or sudo is used for this command
if Process.euid != 0
  throw "Must run this script as root or use sudo."
end

# Was a project name specified?
if ARGV[0]
  u = ARGV[0]
else
  puts "User name or ID is required"
  exit 1
end

# Objects
novadb = NovaDB2.new
users = Users.new

# Get the OpenStack Query Library
os_release = novadb.get_openstack_release
require "openstack/#{os_release}"
openstack = Object.const_get(os_release.capitalize).new

user = users.fuzzy_search(u)
user_name = user.values[0]
user_id = user.keys[0]

puts "User: #{user_name}"
puts "ID: #{user_id}"
puts ""

puts "Projects"
users.projects(user_id).each do |project|
  puts "* #{project}"
end
puts ""

novadb.regions.each do |region, creds|
  rows = openstack.instances_by_user(user_id, region)
  puts "Instances in #{region} (#{rows.count})"
  rows.each do |row|
    puts "* #{row[:display_name]}"
  end
  puts ""

  rows = openstack.volumes_by_user(user_id, region)
  puts "Volumes in #{region} (#{rows.count})"
  rows.each do |row|
    puts "* #{row[:display_name]}"
  end
  puts ""
end
