#!/usr/bin/env ruby
$:.unshift File.expand_path("../../share/novac/lib/rb", __FILE__)
require 'rubygems'
require 'novadb2'
require 'helpers/quotas'

# variables
project_id = ARGV[0]
limit = ARGV[1]
quotas = Quotas.new

quotas.set_project_quota_in_all_regions(project_id, 'images', limit)
