#!/usr/bin/env ruby

# Usage: novac quota-get-used-resources <project id> [resource]
# Summary: Show quota usage for a project - optionally specify a single resource.
# Help: resource is an optional argument.

$:.unshift File.expand_path("../../share/novac/lib/rb", __FILE__)
require 'rubygems'
require 'novadb'
require 'quotas'

# variables
project_id = ARGV[0]

if ARGV.length > 1
  resource = ARGV[1]
else
  resource = nil
end

quotas = Quotas.new
resources = quotas.get_used_resources(project_id)

if resource
  puts resources(project_id)[resource]
else
  resources.each do |r, v|
    puts "#{r} #{v}"
  end
end
