#!/usr/bin/env ruby

# Usage: novac quota-snafu
# Summary: Lists all users who have exceeded their quota. Very similar to novac quota-report.

$:.unshift File.expand_path("../../share/novac/lib/rb", __FILE__)
require 'rubygems'
require 'novadb'
require 'quotas'
require 'projects'

# List of required libraries
required_libs = ['terminal-table']

# Try to load each of the libraries
# Fail if unable to and list what libs are needed
begin
  required_libs.each { |l| require l }
rescue LoadError
  puts "This script needs the following external libraries: "
  required_libs.each { |l| puts " * #{l}" }
  exit 1
end

# Ensure root or sudo is used for this command
if Process.euid != 0
  throw "Must run this script as root or sudo."
end

# Was a project specified?
if ARGV[0]
  p = ARGV[0]
else
  p = nil
end

# create quota object
quotas = Quotas.new

# Build a list of project quotas
if p
  projects = Projects.new.fuzzy_search(p)
else
  projects = Projects.new.projects
end

# Get the quota for each project
# As well as resources used
quota = {}
resources_used = {}
to_report = {}
total_usage = {}

projects.each do |project_id, project_name|
  total_usage[project_id] = quotas.get_project_usage(project_id)
  to_report[project_id] = project_name
  quota[project_id] = quotas.project_quota(project_id)
end

# Report quota usage
x = to_report.sort_by { |k,v| v }
x.each do |project_id, project_name|
  rows = []
  q = quota[project_id].sort_by { |k,v| k }
  q.each do |resource, limit|
    used = 0
    total_usage[project_id]['global'].each do |r, v|
      if r == resource
        used = v
      end
    end
    total_usage[project_id]['users'].each do |user, user_info|
      user_info.each do |r, v|
        if r == resource
          used += v
        end
      end
    end

    # Catch 0 or unlimited quota users
    if limit.to_f > 0.0
      percent = ((used.to_f / limit.to_f) * 100).to_i
    else
      percent = 0
    end
    if percent > 100
      rows << [resource,used,limit,"#{percent} %"]
    end
  end
  next unless rows.any?
  table = Terminal::Table.new :title => project_name, :headings => ['Resource', 'Used', 'Limit',''], :rows => rows, :style => { :width => 80 }
  table.align_column(-1, :right)
  table.align_column(-2, :right)
  table.align_column(-3, :right)

  puts table
end
