#!/usr/bin/env ruby
$:.unshift File.expand_path("../../share/novac/lib/rb", __FILE__)
require 'rubygems'
require 'novadb2'
require 'helpers/quotas'

# variables
project_id = ARGV[0]
limit = ARGV[1]

quotas = Quotas.new

puts quotas.project_quota_with_defaults(project_id)['images']
