#!/usr/bin/env ruby

# Usage: novac cloud-user-metrics
# Summary: Print tenant usage for the past 24 hour in collectd format
# Help: Print tenant usage for the past 24 hour in collectd format

$:.unshift File.expand_path("../../share/novac/lib/rb", __FILE__)
require 'rubygems'
require 'helpers/projects'

# https://raw.github.com/stackforge/cookbook-openstack-common/master/libraries/parse.rb
def prettytable_to_array table
  ret = []
  return ret if table == nil
  indicies = []
  (table.split(/$/).collect{|x| x.strip}).each { |line|
    unless line.start_with?('+--') or line.empty?
      cols = line.split('|').collect{|x| x.strip}
      cols.shift
      if indicies == []
        indicies = cols
        next
      end
      newobj = {}
      cols.each { |val|
        newobj[indicies[newobj.length]] = val
      }
      ret.push(newobj)
    end
  }
  # this kinda sucks, but some prettytable data comes
  # as Property Value pairs. If this is the case, then
  # flatten it as expected.
  newobj = {}
  if indicies == ['Property', 'Value']
    ret.each { |x|
      newobj[x['Property']] = x['Value']
    }
    [newobj]
  else
    ret
  end
end

location = %x{ facter location }.chomp
projects = Projects.new

now = Time.now
midnight = Time.new(now.year, now.month, now.day, 0, 0, 0, '+00:00')

250.downto(0) do |day|
  today = midnight - (day.to_i * 86400)
  t = today.to_i
  yesterday = today - 86400

  #puts today.strftime("%Y-%m-%d")
  #puts yesterday.strftime("%Y-%m-%d")

  #today = Time.now
  #yesterday = today - 86400

  command = ". ~/openrc; /usr/bin/nova usage-list --start #{yesterday.strftime("%Y-%m-%d")} --end #{today.strftime("%Y-%m-%d")}"
  output = %x{ #{command} }

  project_usage = {}

  usages = prettytable_to_array(output)
  usages.each do |usage|
    project_usage[usage['Tenant ID']] = usage
  end

  total_instances = 0
  total_memory = 0
  total_cpu = 0
  total_disk = 0

  projects.projects.keys.each do |project_id|
    if project_usage.key?(project_id)
      instances = project_usage[project_id]['Instances'].to_i
      memory = project_usage[project_id]['RAM MB-Hours'].to_i / 24 / 1024
      cpu = project_usage[project_id]['CPU Hours'].to_i / 24
      disk = project_usage[project_id]['Disk GB-Hours'].to_i / 24
      #volume = %x{ /root/novac/bin/novac quota-get-used-resources #{project_id} gigabytes }.chomp if location == 'alberta'
    else
      instances = 0
      memory = 0
      cpu = 0
      disk = 0
      #volume = %x{ /root/novac/bin/novac quota-get-used-resources #{project_id} gigabytes }.chomp if location == 'alberta'
    end

    total_instances += instances
    total_memory += memory
    total_cpu += cpu
    total_disk += disk

    puts "projects.#{project_id}.cloud_usage.#{location}.instances #{instances} #{t}"
    puts "projects.#{project_id}.cloud_usage.#{location}.memory #{memory} #{t}"
    puts "projects.#{project_id}.cloud_usage.#{location}.cpu #{cpu} #{t}"
    puts "projects.#{project_id}.cloud_usage.#{location}.disk #{disk} #{t}"
  end

  puts "cloud_usage.#{location}.instances #{total_instances} #{t}"
  puts "cloud_usage.#{location}.memory #{total_memory} #{t}"
  puts "cloud_usage.#{location}.cpu #{total_cpu} #{t}"
  puts "cloud_usage.#{location}.disk #{total_disk} #{t}"

  sleep 0.5
end
