#!/usr/bin/env ruby

$:.unshift File.expand_path("../../share/novac/lib/rb", __FILE__)
require 'mysql2'
require 'rubygems'
require 'terminal-table'
require 'novadb2'
require 'helpers/projects'
require 'csv'

# Ensure root or sudo is used for this command
if Process.euid != 0
  throw "Must run this script as root or use sudo."
end

# Get the region and an optional logrotated file
region = %x{ facter location }.chomp

file = ""
if ARGV.length > 0
  file = ".#{ARGV[0].downcase}"
end

if region != "alberta" && region != "quebec"
  puts "Must either specify alberta or quebec"
  exit 1
end

novadb = NovaDB2.instance
db = novadb.clouds[region]['mysql']['nova']
api_db = Mysql2::Client.new( :host => db[:host], :username => db[:user], :password => db[:password], :database => 'api_reports' )

# Get the OpenStack Query Library
os_release = novadb.get_openstack_release
require "openstack/#{os_release}"
openstack = Object.const_get(os_release.capitalize).new

projects = Projects.new.projects
rows = []

# Add tenant names to ignore here
ignore_projects = ["nagioscheck"]

# Build a map of services and how to parse their log files
api_queries = {
  'nova' => "zgrep nova.osapi_compute.wsgi.server /opt/rsyslog/nova.log#{file} | awk '{print $2, $3, $4, $10, $11, $12, $13}' | sed -e 's/\]//g' -e 's/,127.0.0.1//g' -e 's/\"//g'",
  'cinder' =>  "zgrep eventlet.wsgi.server /opt/rsyslog/cinder.log#{file} | awk '{print $2, $3, $4, $10, $14, $19, $20}'  | grep -v accepted | sed -e 's/,127.0.0.1//g' -e 's/\"//g'",
  'swift' => "zgrep -E 'GET|POST|PUT|DELETE' /opt/rsyslog/swift.log#{file} | awk '{print $2, $4, $6, $7, $8}' | grep -v headers",
}

# Swift tenant IDs must be pulled from a substring
swift_tenant_id_re = /AUTH_([a-z0-9]+)/

# For each of the services, parse their log files
# Store the result in "rows"
file_date = nil
api_queries.each do |api, query|
  output = `#{query}`
  output.split("\n").each do |row|

    begin
      case api
      when "swift"
        server, ip, date, req_type, req = row.split
        day, month, year, hour, minute, second = date.split('/')
        date = Time.utc(year, month, day, hour, minute, second).getlocal.strftime("%Y/%m/%d/%H/%M/%S")
        year, month, day, hour, minute, second = date.split('/')
        time = "#{hour}:#{minute}:#{second}"
        match = req.match swift_tenant_id_re
        tenant_id = match[1]
        tenant_name = projects[tenant_id]
      else
        server, date, time, tenant_id, ips, req_type, req = row.split
        ip = ips.split(',')[0]
        year, month, day = date.split('-')
        time = time.split('.')[0]
        tenant_name = projects[tenant_id]
      end
    rescue
      next
    end

    next if ignore_projects.include?(tenant_name)
    next if req_type == nil
    next if tenant_id == 'GET'
    next if tenant_id == 'wsgi'
    next if tenant_id == '-'
    next if not ['GET', 'POST', 'DELETE', 'PUT', 'HEAD'].include?(req_type)
    #next if ip == '208.75.75.119'

    date_time = "#{date} #{time}"

    begin
      api_db.query "insert ignore into log (log_date, service, tenant_id, ip, request_type, request) VALUES ('#{date_time}', '#{api}', '#{tenant_id}', '#{ip}', '#{req_type}', '#{req}')"
      #puts "insert ignore into log (log_date, service, tenant_id, ip, request_type, request) VALUES ('#{date_time}', '#{api}', '#{tenant_id}', '#{ip}', '#{req_type}', '#{request}')"
    rescue
      next
    end
  end
end
