#!/usr/bin/env ruby
$:.unshift File.expand_path("../../share/novac/lib/rb", __FILE__)
require 'mysql2'
require 'rubygems'
require 'novadb2'
require 'pp'

novadb = NovaDB2.instance
now = Time.now
time = Time.new(now.year, now.month, now.day, now.hour, now.min, 0).getgm.to_i
region = %x{ facter location }.chomp
db = novadb.clouds[region]['mysql']['nova']
instance_metrics = Mysql2::Client.new( :host => db[:host], :username => db[:user], :password => db[:password], :database => 'instance_metrics' )

instances = {}
collection_output = %x{ dsh -g cnodes /usr/local/bin/instance_metrics.rb 2> /dev/null }
collection_output.split("\n").each do |line|
  pieces = line.split(/\s+/)
  uuid = pieces.shift
  metric_category = pieces.shift
  data = {}
  data['uuid'] = uuid
  pieces.each do |p|
    (k,v) = p.split(':')
    data[k] = v
  end
  values = data.values.map { |v| "'#{v}'" }
  insert_query = ""
  if metric_category == 'instance'
    insert_query = "insert ignore into instance (uuid, instance) values (#{values.join(', ')})"
  else
    insert_query = "insert into #{metric_category} (#{data.keys.join(', ')}, timestamp) VALUES (#{values.join(', ')}, '#{time}')"
  end
  begin
    instance_metrics.query insert_query
  rescue
    next
  end

end

