#!/usr/bin/env ruby
$:.unshift File.expand_path("../../share/novac/lib/rb", __FILE__)
require 'rubygems'
require 'novadb2'
require 'helpers/quotas'
require 'helpers/projects'

# variables
project_id = ARGV[0]
limit = ARGV[1]

quotas = Quotas.new
projects = Projects.new.projects
project_name = projects[project_id]

quotas.set_project_quota_in_all_regions(project_id, 'object_mb', limit)

quota_in_bytes = Integer(limit) * 1024 * 1024
command = "\"#{project_name}\" #{quota_in_bytes}"

system("/root/novac/bin/novac swift-set-quota #{command}")
