#!/bin/bash

# Usage: novac swift-set-quota <project> <quota in bytes>
# Summary: Sets a user's swift quota
# Help: Set a project's swift quota to the quota in bytes. Both the <project> and <quota in bytes> are required

if [ "$1" = "" -o "$2" = "" ]; then
  echo "Usage: novac swift-quota-set <project> <quota in bytes>"
  exit 1
fi

source /root/openrc
unset OS_TENANT_NAME
export OS_USERNAME="${1}:admin"
export OS_TENANT_ID=$1

grep \\[mysql /etc/novac/config.ini | grep nova | cut -d: -f2 | while read line
do
  export OS_REGION_NAME=$line
  swift post -m quota-bytes:$2
done
