#!/usr/bin/env ruby
# Usage: novac quota-balance
# # Summary: Balance quotas between regions. This is normally run by cron.
# # Help: novac balance-quotas

$:.unshift File.expand_path("../../share/novac/lib/rb", __FILE__)
require 'rubygems'
require 'novadb'
require 'quotas'
require 'projects'

# List of required libraries
required_libs = []

# Try to load each of the libraries
# Fail if unable to and list what libs are needed
begin
  required_libs.each { |l| require l }
rescue LoadError
  puts "This script needs the following external libraries: "
  required_libs.each { |l| puts " * #{l}" }
  exit 1
end

# Ensure root or sudo is used for this command
if Process.euid != 0
  throw "Must run this script as root or sudo."
end

# create quota object
quotas = Quotas.new

quotas.balance_all_quotas
