#!/usr/bin/env python

import os, sys, argparse
sys.path.append(os.path.abspath(__file__) + "/../../share/novac/lib")

import novadb

parser = argparse.ArgumentParser()
parser.add_argument('instance_name', nargs='?', help='instance name, uuid, or instance id of a node')
parser.add_argument('project_id', nargs='?', help='the project_id to constrain the statement to')
args = parser.parse_args()

where = " WHERE " + novadb.instance_name_constraint(args.instance_name)
where += " AND project_id = '%s'" % args.project_id
results = novadb.execute("SELECT display_name, hostname, display_description FROM instances" + where)

print(results)