#!/usr/bin/env python

import os, sys, argparse
sys.path.append(os.path.dirname(os.path.abspath(__file__)) + "/../share/novac/lib")

import novadb

parser = argparse.ArgumentParser()
parser.add_argument('instance_name', nargs='?', help='instance name, uuid, or instance id of a node')
parser.add_argument('project_id', nargs='?', help='the project_id to constrain the statement to')
args = parser.parse_args()

where = novadb.instance_name_constraint(args.instance_name)
where += " AND project_id = '%s'" % args.project_id
setcols = "display_name = '%(instance_name)s', hostname = '%(instance_name)s', display_description = '%(instance_name)s'" % locals()
novadb.execute("UPDATE instances SET " + setcols + " WHERE " + where)
