#!/usr/bin/env ruby

# Usage: novac list-users [userID]
# Summary: List all users, and their role with each associated project. (Helps locate 'admin' users). It hides our system users by default.
# Help: userID is an optional argument. If specified it can either be a user's UUID or 'all' to not hide system users/roles.

$:.unshift File.expand_path("../../share/novac/lib/rb", __FILE__)
require 'rubygems'
require 'helpers/users'

required_libs = ['terminal-table','mysql2']

# Try to load each of the libraries
# Fail if unable to and list what libs are needed
begin
  required_libs.each { |l| require l }
rescue LoadError
  puts "This script needs the following external libraries: "
  required_libs.each { |l| puts " * #{l}" }
  exit 1
end

# Ensure root or sudo is used for this command
if Process.euid != 0
  throw "Must run this script as root or use sudo."
end

# Load Users and Projects
users = Users.new

# Was a user ID specified (ID or 'all')
if ARGV[0]
  user = ARGV[0]
else
  user = nil
end

require 'pp'
rows = []
headings = ['ID', 'Username', 'Project', 'Role']
users.list_user_roles(user).each do |user, projects|
  projects.each do |project, project_info|
    next if ['nova', 'glance', 'cinder', 'swift', 'admin'].include?(users.users[user])
    #next if ['_member_', 'Member'].include?(project_info['role_name'])
    rows << [user, users.users[user], project_info['project_name'], project_info['role_name']]
  end
end

puts Terminal::Table.new :headings => headings, :rows => rows
