#!/usr/bin/env ruby
$:.unshift File.expand_path("../../share/novac/lib/rb", __FILE__)
require 'rubygems'
require 'novadb2'
require 'helpers/quotas'

# variables
project_id = ARGV[0]
quotas = Quotas.new

object_mb = quotas.project_quota(project_id)['object_mb']
if object_mb
  puts object_mb
else
  puts 0
end
